/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTLIT = 20;
  /** RegularExpression Id. */
  int DIGIT = 21;
  /** RegularExpression Id. */
  int IDENT = 22;
  /** RegularExpression Id. */
  int BEGIN = 23;
  /** RegularExpression Id. */
  int LETTER = 24;
  /** RegularExpression Id. */
  int OPEN = 25;
  /** RegularExpression Id. */
  int CLOSE = 26;
  /** RegularExpression Id. */
  int LT = 27;
  /** RegularExpression Id. */
  int LTEQ = 28;
  /** RegularExpression Id. */
  int GT = 29;
  /** RegularExpression Id. */
  int GTEQ = 30;
  /** RegularExpression Id. */
  int NEQ = 31;
  /** RegularExpression Id. */
  int EQEQ = 32;
  /** RegularExpression Id. */
  int LAND = 33;
  /** RegularExpression Id. */
  int LOR = 34;
  /** RegularExpression Id. */
  int ADD = 35;
  /** RegularExpression Id. */
  int SUB = 36;
  /** RegularExpression Id. */
  int MUL = 37;
  /** RegularExpression Id. */
  int DIV = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\";\"",
    "\"void\"",
    "\",\"",
    "\"print\"",
    "\"return\"",
    "\"while\"",
    "\"{\"",
    "\"}\"",
    "\"if\"",
    "\"else\"",
    "\"=\"",
    "\"int\"",
    "\"boolean\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 18>",
    "<token of kind 19>",
    "<INTLIT>",
    "<DIGIT>",
    "<IDENT>",
    "<BEGIN>",
    "<LETTER>",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"!=\"",
    "\"==\"",
    "\"&&\"",
    "\"||\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
