/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTLIT = 19;
  /** RegularExpression Id. */
  int DIGIT = 20;
  /** RegularExpression Id. */
  int IDENT = 21;
  /** RegularExpression Id. */
  int BEGIN = 22;
  /** RegularExpression Id. */
  int LETTER = 23;
  /** RegularExpression Id. */
  int OPEN = 24;
  /** RegularExpression Id. */
  int CLOSE = 25;
  /** RegularExpression Id. */
  int LT = 26;
  /** RegularExpression Id. */
  int LTEQ = 27;
  /** RegularExpression Id. */
  int GT = 28;
  /** RegularExpression Id. */
  int GTEQ = 29;
  /** RegularExpression Id. */
  int NEQ = 30;
  /** RegularExpression Id. */
  int EQEQ = 31;
  /** RegularExpression Id. */
  int LAND = 32;
  /** RegularExpression Id. */
  int LOR = 33;
  /** RegularExpression Id. */
  int ADD = 34;
  /** RegularExpression Id. */
  int SUB = 35;
  /** RegularExpression Id. */
  int MUL = 36;
  /** RegularExpression Id. */
  int DIV = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"print\"",
    "\";\"",
    "\"return\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"int\"",
    "\"boolean\"",
    "\"=\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 17>",
    "<token of kind 18>",
    "<INTLIT>",
    "<DIGIT>",
    "<IDENT>",
    "<BEGIN>",
    "<LETTER>",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"!=\"",
    "\"==\"",
    "\"&&\"",
    "\"||\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
