/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTLIT = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;
  /** RegularExpression Id. */
  int IDENT = 17;
  /** RegularExpression Id. */
  int BEGIN = 18;
  /** RegularExpression Id. */
  int LETTER = 19;
  /** RegularExpression Id. */
  int OPEN = 20;
  /** RegularExpression Id. */
  int CLOSE = 21;
  /** RegularExpression Id. */
  int LT = 22;
  /** RegularExpression Id. */
  int LTEQ = 23;
  /** RegularExpression Id. */
  int GT = 24;
  /** RegularExpression Id. */
  int GTEQ = 25;
  /** RegularExpression Id. */
  int NEQ = 26;
  /** RegularExpression Id. */
  int EQEQ = 27;
  /** RegularExpression Id. */
  int LAND = 28;
  /** RegularExpression Id. */
  int LOR = 29;
  /** RegularExpression Id. */
  int ADD = 30;
  /** RegularExpression Id. */
  int SUB = 31;
  /** RegularExpression Id. */
  int MUL = 32;
  /** RegularExpression Id. */
  int DIV = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"print\"",
    "\"return\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"int\"",
    "\"bool\"",
    "\"=\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 13>",
    "<token of kind 14>",
    "<INTLIT>",
    "<DIGIT>",
    "<IDENT>",
    "<BEGIN>",
    "<LETTER>",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"!=\"",
    "\"==\"",
    "\"&&\"",
    "\"||\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
